package models

type QuestFlag int

const (
	Act1PrologueSeen QuestFlag = iota
	DenOfEvilComplete
	SistersBurialGroundsComplete
	ToolsOfTheTradeComplete
	TheSearchForCainComplete
	TheForgottenTowerComplete
	SistersToTheSlaughterComplete
	Act1Traversed
	Act2PrologueSeen
	RadamentsLairComplete
	TheHoradricStaffComplete
	TheTaintedSunComplete
	TheArcaneSanctuaryComplete
	TheSummonerComplete
	TheSevenTombsComplete
	Act2Traversed
	Act3PrologueSeen
	LamEsenTomeComplete
	KhalimsWillComplete
	BladeOfTheOldReligionComplete
	TheGoldenBirdComplete
	TheBlackenedTempleComplete
	TheGuardianComplete
	Act3Traversed
	Act4PrologueSeen
	TheFallenAngelComplete
	TerrorsEndComplete
	TheHellforgeComplete
	Act4Traversed
	RogueWarningComplete
	GuardInTownWarningComplete
	GuardInDesertWarningComplete
	DarkWandererSeen
	AngelWarningComplete
	Act5PrologueSeen
	SiegeOnHarrogathComplete
	RescueOnMountArreatComplete
	PrisonOfIceComplete
	BetrayalOfHarrogathComplete
	RiteOfPassageComplete
	EveOfDestructionComplete
	RespecFromAkaraComplete
)
