package models

type LevelData struct {
	Name         string
	Id           int
	Pal          int
	Act          int
	QuestFlag    QuestFlag
	QuestFlagEx  QuestFlag
	Layer        int
	SizeX        int
	SizeXN       int
	SizeXH       int
	SizeY        int
	SizeYN       int
	SizeYH       int
	OffsetX      int
	OffsetY      int
	Depend       int
	Teleport     int
	Rain         int
	Mud          int
	NoPer        int
	LOSDraw      int
	FloorFilter  int
	BlankScreen  int
	DrawEdges    int
	DrlgType     DynamicRandomLevelGenerationType
	LevelType    int
	SubType      SubType
	SubWaypoint  SubType
	SubShrine    SubType
	Vis0         int
	Vis1         int
	Vis2         int
	Vis3         int
	Vis4         int
	Vis5         int
	Vis6         int
	Vis7         int
	Warp0        WarpCode
	Warp1        WarpCode
	Warp2        WarpCode
	Warp3        WarpCode
	Warp4        WarpCode
	Warp5        WarpCode
	Warp6        WarpCode
	Warp7        WarpCode
	Intensity    int
	Red          int
	Green        int
	Blue         int
	Portal       int
	Position     int
	SaveMonsters int
	Quest        QuestFlag
	WarpDist     int
	MonLvl       int
	MonLvlN      int
	MonLvlH      int
	MonLvlEx     int
	MonLvlExN    int
	MonLvlExH    int
	MonDen       int
	MonDenN      int
	MonDenH      int
	MonUMin      int
	MonUMinN     int
	MonUMinH     int
	MonUMax      int
	MonUMaxN     int
	MonUMaxH     int
	MonWndr      int
	MonSpcWalk   int
	NumMon       int
	// Add mon1 to mon25, nmon1 to nmon25, umon1 to umon25 based on the data.
	cmon1  int
	cmon2  int
	cmon3  int
	cmon4  int
	cpct1  int
	cpct2  int
	cpct3  int
	cpct4  int
	camt1  int
	camt2  int
	camt3  int
	camt4  int
	Themes int
	// Add SoundEnv based on SoundEnviron.txt data.
	Waypoint   int
	LevelName  string
	LevelWarp  string
	LevelEntry string
	// Add ObjGrp0 to ObjGrp7, ObjPrb0 to ObjPrb7 based on Objgroup.txt data.
	LevelGroup int
}
