-- print("testing asset loader...")
-- data = assets.load("/data/global/ui/Loading/loadingscreen.dc6")

--[[
 -- Access the Sounds array
for i, sound in ipairs(records.Sounds) do
    print("Sound " .. i .. ": Sound=" .. sound.Sound .. " FileName=" .. sound.FileName)
end

 -- Access the Belts array
for i, belt in ipairs(records.Belts) do
    print("Belt " .. i .. ": Name=" .. belt.name .. " NumBoxes=" .. belt.numboxes)
end
]]

print("Belts: " .. #records.Belts)
print("CharStartingAttributes: " .. #records.CharStartingAttributes)
print("Inventory: " .. #records.Inventory)
print("Overlays: " .. #records.Overlays)
print("PetTypes: " .. #records.PetTypes)
print("AutoMapEntries: " .. #records.AutoMapEntries)
print("States: " .. #records.States)
print("Hirelings: " .. #records.Hirelings)
print("HirelingDescriptions: " .. #records.HirelingDescriptions)
print("Missiles: " .. #records.Missiles)
print("DifficultyLevels: " .. #records.DifficultyLevels)
print("Shrines: " .. #records.Shrines)
print("GambleRecords: " .. #records.GambleRecords)
print("NpcTradeRecords: " .. #records.NpcTradeRecords)
print("ExperienceBreakpoints: " .. #records.ExperienceBreakpoints)
print("ItemArmor: " .. #records.ItemArmor)
print("ItemWeapon: " .. #records.ItemWeapon)
print("ItemWeaponClass: " .. #records.ItemWeaponClass)
print("ItemMisc: " .. #records.ItemMisc)
print("ItemTypes: " .. #records.ItemTypes)
print("ItemAutoMagic: " .. #records.ItemAutoMagic)
print("ItemStatCost: " .. #records.ItemStatCost)
print("ItemRatio: " .. #records.ItemRatio)
print("ItemUnique: " .. #records.ItemUnique)
print("ItemHiQualityMods: " .. #records.ItemHiQualityMods)
print("ItemProperties: " .. #records.ItemProperties)
print("CubeRecipes: " .. #records.CubeRecipes)
print("Books: " .. #records.Books)
print("Gems: " .. #records.Gems)
print("Runes: " .. #records.Runes)
print("SetItems: " .. #records.SetItems)
print("SetBonuses: " .. #records.SetBonuses)
print("Skills: " .. #records.Skills)
print("SkillDesc: " .. #records.SkillDesc)
print("Treasures: " .. #records.Treasures)
print("TreasuresExpansion: " .. #records.TreasuresExpansion)
print("MagicPrefixes: " .. #records.MagicPrefixes)
print("MagicSuffixes: " .. #records.MagicSuffixes)
print("RarePrefixes: " .. #records.RarePrefixes)
print("RareSuffixes: " .. #records.RareSuffixes)
print("UniquePrefixes: " .. #records.UniquePrefixes)
print("UniqueSuffixes: " .. #records.UniqueSuffixes)
print("Objects: " .. #records.Objects)
print("ObjectTypes: " .. #records.ObjectTypes)
print("ObjectGroups: " .. #records.ObjectGroups)
print("ObjectModes: " .. #records.ObjectModes)
print("Sounds: " .. #records.Sounds)
print("SoundEnvironments: " .. #records.SoundEnvironments)
print("LevelPresets: " .. #records.LevelPresets)
print("LevelType: " .. #records.LevelType)
print("LevelWarp: " .. #records.LevelWarp)
print("LevelDetails: " .. #records.LevelDetails)
print("LevelMaze: " .. #records.LevelMaze)
print("LevelSubstitutions: " .. #records.LevelSubstitutions)
print("MonsterUniqueModifiers: " .. #records.MonsterUniqueModifiers)
print("MonsterEquipment: " .. #records.MonsterEquipment)
print("MonsterLevelStats: " .. #records.MonsterLevelStats)
print("MonsterPresets: " .. #records.MonsterPresets)
print("MonsterProperties: " .. #records.MonsterProperties)
print("MonsterSequences: " .. #records.MonsterSequences)
print("MonsterStats: " .. #records.MonsterStats)
print("MonsterStats2: " .. #records.MonsterStats2)
print("MonsterSounds: " .. #records.MonsterSounds)
print("MonsterUniqueNames: " .. #records.MonsterUniqueNames)

