package recordManager

const (
	PathLevelPreset           = "/data/global/excel/LvlPrest.txt"
	PathLevelType             = "/data/global/excel/LvlTypes.txt"
	PathObjectType            = "/data/global/excel/objtype.txt"
	PathLevelWarp             = "/data/global/excel/LvlWarp.txt"
	PathLevelDetails          = "/data/global/excel/Levels.txt"
	PathLevelMaze             = "/data/global/excel/LvlMaze.txt"
	PathLevelGroups           = "/data/global/excel/LevelGroups.txt"
	PathLevelSubstitutions    = "/data/global/excel/LvlSub.txt"
	PathObjectDetails         = "/data/global/excel/Objects.txt"
	PathObjectMode            = "/data/global/excel/ObjMode.txt"
	PathObjectGroup           = "/data/global/excel/objgroup.txt"
	PathSoundSettings         = "/data/global/excel/Sounds.txt"
	PathItemStatCost          = "/data/global/excel/ItemStatCost.txt"
	PathItemRatio             = "/data/global/excel/itemratio.txt"
	PathItemTypes             = "/data/global/excel/ItemTypes.txt"
	PathQualityItems          = "/data/global/excel/qualityitems.txt"
	PathOverlays              = "/data/global/excel/Overlay.txt"
	PathRunes                 = "/data/global/excel/runes.txt"
	PathSets                  = "/data/global/excel/Sets.txt"
	PathSetItems              = "/data/global/excel/SetItems.txt"
	PathAutoMagic             = "/data/global/excel/automagic.txt"
	PathProperties            = "/data/global/excel/Properties.txt"
	PathHireling              = "/data/global/excel/hireling.txt"
	PathHirelingDescription   = "/data/global/excel/HireDesc.txt"
	PathDifficultyLevels      = "/data/global/excel/difficultylevels.txt"
	PathAutoMap               = "/data/global/excel/AutoMap.txt"
	PathCubeRecipes           = "/data/global/excel/cubemain.txt"
	PathSkills                = "/data/global/excel/skills.txt"
	PathSkillDesc             = "/data/global/excel/skilldesc.txt"
	PathTreasureClass         = "/data/global/excel/TreasureClass.txt"
	PathTreasureClassEx       = "/data/global/excel/TreasureClassEx.txt"
	PathStates                = "/data/global/excel/states.txt"
	PathSoundEnvirons         = "/data/global/excel/soundenviron.txt"
	PathShrines               = "/data/global/excel/shrines.txt"
	PathPetType               = "/data/global/excel/pettype.txt"
	PathNPC                   = "/data/global/excel/npc.txt"
	PathMonsterUniqueModifier = "/data/global/excel/monumod.txt"
	PathMonsterEquipment      = "/data/global/excel/monequip.txt"
	PathUniqueAppellation     = "/data/global/excel/UniqueAppellation.txt"
	PathMonsterLevel          = "/data/global/excel/monlvl.txt"
	PathMonsterPreset         = "/data/global/excel/MonPreset.txt"
	PathMonsterProperties     = "/data/global/excel/MonProp.txt"
	PathMonsterStats          = "/data/global/excel/monstats.txt"
	PathMonsterStats2         = "/data/global/excel/monstats2.txt"
	PathMonsterSound          = "/data/global/excel/monsounds.txt"
	PathMonsterSequence       = "/data/global/excel/monseq.txt"
	PathBelts                 = "/data/global/excel/belts.txt"
	PathGamble                = "/data/global/excel/gamble.txt"
	PathInventory             = "/data/global/excel/inventory.txt"
	PathWeapons               = "/data/global/excel/weapons.txt"
	PathArmor                 = "/data/global/excel/armor.txt"
	PathWeaponClass           = "/data/global/excel/WeaponClass.txt"
	PathBooks                 = "/data/global/excel/books.txt"
	PathMisc                  = "/data/global/excel/misc.txt"
	PathUniqueItems           = "/data/global/excel/UniqueItems.txt"
	PathGems                  = "/data/global/excel/gems.txt"
	PathMagicPrefix           = "/data/global/excel/MagicPrefix.txt"
	PathMagicSuffix           = "/data/global/excel/MagicSuffix.txt"
	PathRarePrefix            = "/data/global/excel/RarePrefix.txt" // these are for item names
	PathRareSuffix            = "/data/global/excel/RareSuffix.txt"
	PathUniquePrefix          = "/data/global/excel/UniquePrefix.txt"
	PathUniqueSuffix          = "/data/global/excel/UniqueSuffix.txt"
	PathExperience            = "/data/global/excel/experience.txt"
	PathCharStats             = "/data/global/excel/charstats.txt"
	PathMissiles              = "/data/global/excel/Missiles.txt"

	// possible d2 resurrected files
	// PathLevelGroups  = "/data/global/excel/LevelGroups.txt"
	// PathObjectPreset = "/data/global/excel/objpreset.txt"

	// just reference files
	// PathBodyLocations   = "/data/global/excel/bodylocs.txt"
	// PathEvents          = "/data/global/excel/events.txt"
	// PathColors          = "/data/global/excel/colors.txt"
	// PathCompCode        = "/data/global/excel/compcode.txt"
	// PathCubeModifier    = "/data/global/excel/CubeMod.txt"
	// PathElemType        = "/data/global/excel/ElemTypes.txt"
	// PathHitClass        = "/data/global/excel/HitClass.txt"
	// PathLowQualityItems = "/data/global/excel/lowqualityitems.txt"
	// PathMissileCalc     = "/data/global/excel/misscalc.txt"
	// PathPlrMode         = "/data/global/excel/PlrMode.txt"
	// PathPlayerType      = "/data/global/excel/PlrType.txt"
	// PathPlayerClass     = "/data/global/excel/PlayerClass.txt"
	// PathSkillCalc       = "/data/global/excel/skillcalc.txt"
	// PathStorePage       = "/data/global/excel/ItemStorePage.txt"
	// PathComposite       = "/data/global/excel/Composit.txt"
	// PathArmorType       = "/data/global/excel/ArmType.txt"
	// PathCubeType        = "/data/global/excel/CubeType.txt" // pretty sure this is some shit they left on accident

	StringTable      = "/data/local/lng/ENG/string.tbl"
	PatchStringTable = "/data/local/lng/ENG/patchstring.tbl"
)
